[tool.black]
target-version = ["py311"]
line-length = 100

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "strict"

[tool.ruff]
target-version = "py311"
line-length = 100
select = [
    "F",
    "W",
    "E",
    "C90",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ANN",
    "ASYNC",
    "BLE",
    "B",
    "A",
    "COM",
    "C4",
    "FA",
    "ISC",
    "G",
    "PIE",
    "PYI",
    "Q",
    "RSE",
    "RET",
    "SLOT",
    "SIM",
    "TID",
    "ARG",
    "PTH",
    "PGH",
    "FLY",
    "PERF",
    "RUF",
]
ignore = [
    "D100",
    "D101",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D203",
    "D212",
    "D401",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "ANN101",
    "ANN102",
    "ANN401",
    "PYI011",
    "PYI021",
    "PYI029",
    "PYI044",
    "PGH003",
]

[tool.ruff.per-file-ignores]
"*.pyi" = ["D418", "A002", "A003"]
